<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="Dashboard">
	<meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
	<title><?php echo $title; ?></title>
	<?php 
    $t = time();
    include 'admincss.phtml';
    ?>
	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
	<section id="container" >
	<!--header start-->
	<header class="header black-bg">
		  <div class="sidebar-toggle-box">
			  <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
		  </div>
		<!--logo start-->
		<a href="javascript:void(0)" class="logo"><b>Inbuzzup Admin</b></a>
		<!--logo end-->
		<div class="top-menu">
			<ul class="nav pull-right top-menu">
				<li><a class="logout" href="/logout" onclick="return confirm('Are you sure you want to logout?')">Logout</a></li>
			</ul>
		</div>
	</header>
	<!--header end-->
	<!--sidebar start-->
	<?php include 'sidebar.phtml'; ?>
	<!--sidebar end-->
	<?php echo $this->content;  ?>
	</section>
	<?php
    include 'adminjs.phtml';
    ?>
</body>

</html>