<aside>
	  <div id="sidebar"  class="nav-collapse ">
		  <!-- sidebar menu start-->
		  <ul class="sidebar-menu" id="nav-accordion">

			  <p class="centered"><a href="profile.html"><img src="/ico/favicon-96x96.png" class="img-circle" width="60"></a></p>
			  <h5 class="centered">Inbuzzup</h5>

			  <!-- <li class="mt">
				  <a href="index.html">
					  <i class="fa fa-dashboard"></i>
					  <span>Dashboard</span>
				  </a>
			  </li> -->
              <?php if(!isset($artistId)) { ?>
              <li>
				  <a href="/menu">
					  <i class="fa fa-bars"></i>
					  <span>Menu</span>
				  </a>
			  </li>
              <li>
				  <a href="/ev/artists">
					  <i class="fa fa-user"></i>
					  <span>Artists</span>
				  </a>
			  </li>
              <li class="sub-menu">
                      <a href="javascript:;" >
                          <i class="fa fa-calendar"></i>
                          <span>Event</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="/ev">View events</a></li>
                          <li><a  href="/ev/categories">View Categories</a></li>
                          <li><a  href="/ev/tag">View tags</a></li>
                          <li><a  href="/venue">View venus</a></li>
                      </ul>
              </li>
              <li>
				  <a href="/user">
					  <i class="fa fa-users"></i>
					  <span>Users</span>
				  </a>
			  </li>
              <li>
				  <a href="/user/booking">
					  <i class="fa fa-flag"></i>
					  <span>Bookings</span>
				  </a>
			  </li>
              <li>
				  <a href="/ev/media">
					  <i class="fa fa-upload"></i>
					  <span>Media</span>
				  </a>
			  </li>
              <li>
				  <a href="/article">
					  <i class="fa fa-newspaper-o"></i>
					  <span>Backstage</span>
				  </a>
			  </li>
              <?php } else { ?>
              <li class="sub-menu">
                      <a href="/ev" >
                          <i class="fa fa-calendar"></i>
                          <span>Event</span>
                      </a>
              </li>
              <?php } ?>
			  <!-- <li class="sub-menu">
				  <a href="javascript:;" >
					  <i class="fa fa-cogs"></i>
					  <span>Components</span>
				  </a>
				  <ul class="sub">
					  <li><a  href="calendar.html">Calendar</a></li>
					  <li><a  href="gallery.html">Gallery</a></li>
					  <li><a  href="todo_list.html">Todo List</a></li>
				  </ul>
			  </li>
			  <li class="sub-menu">
				  <a href="javascript:;" >
					  <i class="fa fa-book"></i>
					  <span>Extra Pages</span>
				  </a>
				  <ul class="sub">
					  <li><a  href="blank.html">Blank Page</a></li>
					  <li><a  href="login.html">Login</a></li>
					  <li><a  href="lock_screen.html">Lock Screen</a></li>
				  </ul>
			  </li>
			  <li class="sub-menu">
				  <a href="javascript:;" >
					  <i class="fa fa-tasks"></i>
					  <span>Forms</span>
				  </a>
				  <ul class="sub">
					  <li><a  href="form_component.html">Form Components</a></li>
				  </ul>
			  </li>
			  <li class="sub-menu">
				  <a class="active" href="javascript:;" >
					  <i class="fa fa-th"></i>
					  <span>Data Tables</span>
				  </a>
				  <ul class="sub">
					  <li><a  href="basic_table.html">Basic Table</a></li>
					  <li class="active"><a  href="responsive_table.html">Responsive Table</a></li>
				  </ul>
			  </li>
			  <li class="sub-menu">
				  <a href="javascript:;" >
					  <i class=" fa fa-bar-chart-o"></i>
					  <span>Charts</span>
				  </a>
				  <ul class="sub">
					  <li><a  href="morris.html">Morris</a></li>
					  <li><a  href="chartjs.html">Chartjs</a></li>
				  </ul>
			  </li> -->

		  </ul>
		  <!-- sidebar menu end-->
	  </div>
	</aside>