<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword"
	content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
 <meta http-equiv="cache-control" content="max-age=0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
<meta http-equiv="pragma" content="no-cache" />


    <title>Admin| Backend</title>
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->basePath('img/front/favicon.ico') ?>" />
    <?php
    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    include_once("backendcss.phtml");
    ?>

</head>
<body>
	<section id="container">
		<?php include 'header.phtml';
           include_once('sidebar.phtml');
	       echo $this->content;
	 ?>
	</section>
	<?php include_once('backendjs.phtml');?>
</body>
</html>
