<aside>
	<div id="sidebar" class="nav-collapse ">
		<!-- sidebar menu start-->
		<ul class="sidebar-menu" id="nav-accordion">
			<p class="centered">
				<a class='logo_class'><img src="../../images/admin/user.png"
					class="img-circle" width="60">
				</a>
			</p>
			<h5 class="centered">
				<?php echo "Admin"?></h5>

            <li class='banner common_class'><a title="Details of Mykidzday Banner"
				class="common_class banner"> <i class="fa fa-area-chart"></i> <span>Banner management</span>
			</a></li>
            <li class='contact common_class'><a title="Details of Mykidzday Contact"
				class="common_class contact"> <i class="fa fa-area-chart"></i> <span>Contact management</span>
			</a></li>
            <li class='carrer common_class'><a title="Details of Mykidzday Carrer"
				class="common_class carrer"> <i class="fa fa-area-chart"></i> <span>Carrer management</span>
			</a></li>
            <li class='user common_class'><a title="Details of Mykidzday Users"
				class="common_class user"> <i class="fa fa-user"></i> <span>User management</span>
			</a></li>
            <li class='driver common_class'><a title="Details of Mykidzday Driver"
				class="common_class driver"> <i class="fa fa-area-chart"></i> <span>Driver management</span>
			</a></li>
            <li class='officeAddress common_class'><a title="Details of Mykidzday Office address"
				class="common_class officeAddress"> <i class="fa fa-area-chart"></i> <span>Office address management</span>
			</a></li>
            <li class='coupon common_class'><a title="Details of Mykidzday Coupon"
				class="common_class coupon"> <i class="fa fa-area-chart"></i> <span>Coupon management</span>
			</a></li>
            <li class='officeList common_class'><a title="Details of Mykidzday Office and driver list "
				class="common_class officeList"> <i class="fa fa-area-chart"></i> <span>Office and driver list management</span>
			</a></li>
            <li class='payment common_class'><a title="Details of Mykidzday Payment"
				class="common_class payment"> <i class="fa fa-area-chart"></i> <span>Payment management</span>
			</a></li>
            <li class='van common_class'><a title="Details of Mykidzday Van"
				class="common_class van"> <i class="fa fa-area-chart"></i> <span>Van management</span>
			</a></li>
            <li class='finance common_class'><a title="Details of Mykidzday Finance"
				class="common_class finance"> <i class="fa fa-area-chart"></i> <span>Finance management</span>
			</a></li>
            <li class='order common_class'><a title="Details of Mykidzday Order"
				class="common_class order"> <i class="fa fa-area-chart"></i> <span>Order management</span>
			</a></li>

        <!-- sidebar menu end-->
        </ul>
	</div>
</aside>
