<section>
    <div class="container">
        <div class="featured_section">
            <div class="row">
                <div class="col-lg-12">
                    <div class="col-lg-12">
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="login_form">
                                <h5 class="log_head">Log In</h5>
                                <form class="form-bg" id="signin">
                                    <label>Username or Email</label>
                                    <br>
                                    <input class="input_style" type="text" name="email" value="">
                                    <br>
                                    <label>Password</label>
                                    <br>
                                    <input class="input_style" type="password" name="password" value="">
                                    <br>
                                    <input type="checkbox" name="vehicle" value=""> Remember me
                                    <div>
                                        <input class="log_button loginButton" type="button" value="Login">
                                    </div>

                                </form>
                                <a class="lost-pass" href="#">Lost your password?</a>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="login_form">
                                <h5 class="log_head">Don't have an account? Register and Book!</h5>
                                <form class="form-bg" id="register">
                                    <label>First Name</label>
                                    <br>
                                    <input class="input_style" type="text" id="firstname" name="firstname" value="">
                                    <br>
                                    <label>Lasst Name</label>
                                    <br>
                                    <input class="input_style" type="text" id="lastname" name="lastname" value="">
                                    <br>
                                    <label>Phone Number</label>
                                    <br>
                                    <input class="input_style" type="text" id="phonenumber" name="phonenumber" value="">
                                    <br>
                                    <label>Email</label>
                                    <br>
                                    <input class="input_style" type="text" id="email" name="email"  value="">
                                    <br>
                                    <label>Password</label>
                                    <br>
                                    <input class="input_style" type="password" id="password" name="password" value="">
                                    <br>
                                    <label>Retype Password</label>
                                    <br>
                                    <input class="input_style" type="password" id="confirmpassword" name="confirmpassword" value="">
                                    <br>
                                    <div>
                                        <input class="log_button registerButton" type="button" value="Register">
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>