<!--main content start-->
<section id="main-content">
	<section class="wrapper">
		<h3>
			<i class="fa fa-angle-right"></i> Edit Office Address
		</h3>


		<!-- BASIC FORM ELEMENTS -->
		<div class="row mt">
			<div class="col-lg-12">
				<div class="form-panel">
					<form class="form-horizontal style-form" id='officeContactForm'
						method="post"
						action="/officeaddress/updateaddress" enctype="multipart/form-data">
                        <div class="form-group">
                            <input type="hidden" id="officeId" name="officeId" value="<?php echo $fetchAdrss[0]['office_id']; ?>" />
							<label class="col-sm-2 control-label">Office title :</label>
							<div class="col-sm-10">
								<input type="text" aria-required="true" aria-invalid="true"
									class="form-control errRemove" id="offTitle" name='offTitle' placeholder="Office title" value="<?php echo $fetchAdrss[0]['office_title'];?>" required />
								<label id="errorName" style="margin-right: 10em;"></label>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-sm-2 control-label">Address 1 :<label><label class="col-sm-12"></label><small>(required)</small></label>
                            </label>
							<div class="col-sm-10">
								<input type="text" aria-required="true" aria-invalid="true"
									class="form-control errRemove" id="addrOne" name='addrOne' placeholder="Address 1" value="<?php echo $fetchAdrss[0]['office_address_1'];?>" required />
								<label id="error1" style="margin-right: 10em;"></label>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-sm-2 control-label">Address 2 :<label><label class="col-sm-12"></label><small>(optional)</small></label>
                            </label>
							<div class="col-sm-10">
								<input type="text" aria-required="true" aria-invalid="true"
									class="form-control errRemove" id="addrTwo" name='addrTwo' placeholder="Address 2" value="<?php if(@($fetchAdrss[0]['office_address_2'])) {echo $fetchAdrss[0]['office_address_2'];} else echo "-"; ?>" />
								<label id="error2" style="margin-right: 10em;"></label>
							</div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Office city :<label><label class="col-sm-12"></label><small>(required)</small></label>
                            </label>
                            <div class="col-sm-10">
                                <input type="text" aria-required="true" aria-invalid="true"
									class="form-control errRemove" id="offCity" name='offCity' placeholder="Office city" value="<?php echo $fetchAdrss[0]['office_city'];?>" required />
								<label id="errorCity" style="margin-right: 10em;"></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Office pincode :<label><label class="col-sm-12"></label><small>(required)</small></label>
                            </label>
                            <div class="col-sm-10">
                                <input type="number" aria-required="true" aria-invalid="true"
									class="form-control errRemove" id="offPin" name='offPin' placeholder="Office pincode" value="<?php echo $fetchAdrss[0]['office_pincode'];?>" required />
								<label id="errorPin" style="margin-right: 10em;"></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Office state :<label><label class="col-sm-12"></label><small>(required)</small></label>
                            </label>
                            <div class="col-sm-10">
                                <input type="text" aria-required="true" aria-invalid="true"
									class="form-control errRemove" id="offState" name='offState' placeholder="Office state" value="<?php echo $fetchAdrss[0]['office_state'];?>" required />
								<label id="errorState" style="margin-right: 10em;"></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Office country :<label><label class="col-sm-12"></label><small>(required)</small></label>
                            </label>
                            <div class="col-sm-10">
                                <input type="text" aria-required="true" aria-invalid="true"
									class="form-control errRemove" id="offCon" name='offCon' placeholder="Office country" value="<?php echo $fetchAdrss[0]['office_country'];?>" required />
								<label id="errorCon" style="margin-right: 10em;"></label>
                            </div>
                            <div class="col-sm-10">
                                <input style="margin-left: 10px;" type="button" class="sfp__googleform" value="Show in Map" style="display: block;">
                            </div>
						</div>
                        <div class="form-group">
                            <div class="col-sm-10" style="margin-left: 210px; width: 70%; height: 250px; background-color: lightgrey;">
<!--							<div class="col-sm-10" id="map" style="margin-left: 150px; width: 40%; height: 250px; background-color: lightgrey;">						-->
                                <div id="map">
                                    <img class="image" id="image" src="/upload/bannerimg/Genovia_Location.png" onerror="this.src='/image/profile-deafult-avatar.jpg'" height="250px" width="100%" />
                                </div>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-sm-2 control-label">Office landline :</label>
							<div class="col-sm-10">
								<input type="text" aria-required="true" aria-invalid="true"
									class="form-control errRemove" id="landline" name='landline' placeholder="Office landline" value="<?php if(@($fetchAdrss[0]['office_landline'])) {echo $fetchAdrss[0]['office_landline'];} else echo "-"; ?>" required />
								<label id="errorLand" style="margin-right: 10em;"></label>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-sm-2 control-label">Office phone 1 :</label>
							<div class="col-sm-10">
								<input type="text" aria-required="true" aria-invalid="true"
									class="form-control errRemove" id="phone1" name='phone1' placeholder="Office phone 1" value="<?php echo $fetchAdrss[0]['office_phone_1'];?>" required />
								<label id="errorPhn1" style="margin-right: 10em;"></label>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-sm-2 control-label">Office phone 2 :</label>
							<div class="col-sm-10">
								<input type="text" aria-required="true" aria-invalid="true"
									class="form-control errRemove" id="phone2" name='phone2' placeholder="Office phone 2" value="<?php if(@($fetchAdrss[0]['office_phone_2'])) {echo $fetchAdrss[0]['office_phone_2'];} else echo"-"; ?>" required />
								<label id="errorPhn2" style="margin-right: 10em;"></label>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-sm-2 control-label">Office email :</label>
							<div class="col-sm-10">
								<input type="email" aria-required="true" aria-invalid="true"
									class="form-control errRemove" id="offEmail" name='offEmail' placeholder="Office email" value="<?php if(@($fetchAdrss[0]['office_email'])) {echo $fetchAdrss[0]['office_email'];} else echo "-"; ?>" required />
								<label id="errorEmail" style="margin-right: 10em;"></label>
							</div>
						</div>
                        <input type="hidden" id="lat" name="lat" />
                        <input type="hidden" id="long" name="lat" />
<!--
                        <div class="form-group">
                            <label for="sfp-maps-zoom" class="sfp-label sfp-panel-maps__label">Set Zoom Level:</label>
                            <select class="sfp-select sfp-panel-tracker__select" name="sfp-maps-zoom" id="sfp-maps-zoom">
                                <option selected disabled>Choose here</option>
                                    <?php //for($i=1;$i<=19;$i++){
                                    //echo '<option value="'.$i.'">'.$i.'</option>';
                                    //} ?>
                            </select>
                        </div>
-->
						<div class="col-md-7 temp_btn">
                            <button class="btn_green btn_useradd" type="button" style="margin: 35px !important;" id='addresEdit' value="Save">Update</button>
						</div>
					</form>
				</div>
				<!-- /form-panel -->
			</div>
			<!-- /col-lg-12 -->
		</div>
		<!-- /row -->
	</section>
	<!--wrapper -->
</section>
<!-- /MAIN CONTENT -->
