<section id="main-content">
	<section class="wrapper">
		<h3>
			<i class="fa fa-angle-right"></i> Office Address Details
		</h3>
        <div class="col-sm-12"
			style="margin-bottom: 20px; padding: 0 !important">
				<a href="/officeaddress/add" class="new_user" title="Add new office address">New Office Address</a>
		</div>
		<div class="row mt">
			<div class="col-md-12">
				<div class="content-panel" style="padding-top: 5px;">

					<table class="table table-striped table-advance table-hover tbody datatable sortable"
						name="templateView" id="templateView">

						<thead>
							<tr>
								<td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Name</td>
                                <td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> City</td>
								<td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Pincode</td>
								<td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Phone</td>
								<td style="cursor: pointer; font-weight: bold;"><i
									class="fa fa-bookmark"></i> Action</td>
							</tr>
						</thead>
						<tbody class="my_size">
							<?php if(!empty($fetchData)){
								    foreach($fetchData as $key => $val)
					                   { ?>
							<tr	class="manageAll tempId">

								<td class="hidden-phone"><span class=""
									style="width: 80%; display: inline-block;"><?php echo $val['office_title'];?>
								</span></td>
                                <td class="hidden-phone"><span class=""
									style="width: 80%; display: inline-block;"><?php echo $val['office_city'];?>
								</span></td>
								<td class="hidden-phone"><span class=""
									style="width: 80%; display: inline-block;"><?php echo $val['office_pincode'];?>
								</span></td>
                                <input type="hidden" id="bannerId" name="bannerId" value="<?php echo $val['banner_id']; ?>" />
                                <td class="hidden-phone"><span class=""
									style="width: 80%; display: inline-block;"><?php echo $val['office_phone_1'];?>
								</span></td>
								<td class="temp">
                                    <a href="<?php echo '/officeaddress/edit/'.$val['office_id'];?>" title="Edit address" id="banEdit">
                                            <button class="btn btn-primary btn-xs editBanner">
                                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                            </button>
                                    </a>
									        <button class="btn btn-danger btn-xs delBanner" title="Delete address" data-id="<?php echo $val['office_id']; ?>" >
										        <i class="fa fa-trash-o"></i>
                                    </button>

								</td>
							</tr>
							<?php }
                            }
							else
							{ ?>

                            <tr	class="manageAll tempId">
                                <td></td>
                                <td>
                                    <label style="float: right;"><?php echo "No records found..."; ?></label>
                                </td>
                                <td></td>
                                <td></td>
                            </tr>

							<?php }?>
						</tbody>
					</table>
				</div>
				<!-- /content-panel -->
			</div>
			<!-- /col-md-12 -->
		</div>
		<!-- /row -->

	</section>
	<!-- /wrapper -->

	<!--delete popup-->
	<section id="dynamicpagecreatepopup" class="popupFormForDynamicPage chang_PPopup_conta">
	<div id="" class="chang_PPopup">
    <div class="tab-content" style="border:0px solid;width:490px;">
		<form class="form-popup" style="margin-top: 0px;" method="POST" action="/officeaddress/deladdress" enctype="multipart/form-data">
			 <a class="close" href="javascript:void(0)" onclick="$('#dynamicpagecreatepopup').hide();" style="margin: 10px 10px 0 0px;"><i aria-hidden="true" class="fa fa-times"></i></a>
			<h2 class="form-login-heading">Delete Address</h2>
			<div class="login-wrap" style="overflow:hidden;text-align:center;">
				<input type="hidden" name="hidden_id" value="" class="hidden_id" id="hidden_userid">
				<h4 class="form-login-heading">Are you sure you want to delete this address?</h4>
				<div style="overflow:hidden;display:inline-block;">
                    <input type="button" class="popup_cancel" onclick="$('#dynamicpagecreatepopup').hide();" id="btn"  value="CANCEL"/>
					<input type="submit" class="popup_ok" value="OK"/>
				</div>
			</div>
		</form>
	</div>
    <!--tab-content-->
    </div>
    </section>
    <!-- /delete popup-->

</section>
<!-- /MAIN CONTENT -->
