<section id="main-content">
	<section class="wrapper">
		<h3>
			<i class="fa fa-angle-right"></i> Mykidzday Banner Details
		</h3>
        <div class="col-sm-12"
			style="margin-bottom: 20px; padding: 0 !important">
				<a href="/banner/addbanner" class="new_user" title="Add banner">New Banner</a>
		</div>
		<div class="row mt">
			<div class="col-md-12">
				<div class="content-panel" style="padding-top: 5px;">

					<table class="table table-striped table-advance table-hover tbody datatable sortable"
						name="templateView" id="templateView">

						<thead>
							<tr>
								<td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Banner Image</td>
								<td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Banner name</td>
								<td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Creation date</td>
								<td style="cursor: pointer; font-weight: bold;"><i
									class="fa fa-bookmark"></i> Action</td>
							</tr>
						</thead>
						<tbody class="my_size">
							<?php if(!empty($bannerdata)){
                                    $i=0;
								    foreach($bannerdata as $key => $val)
					                   { $i++;?>
							<tr	class="manageAll tempId">

								<td class="hidden-phone templateImg"><span class="tempImage tmpImg<?php echo $i; ?>"
									style="padding: 5px; font-weight: bold;"><img src="<?php echo $val['banner_image_path'] ?>" onerror="this.src='<?php echo $dynamicPath; ?>/template/demo.jpg'" height="100px" width="100px" />
								</span></td>
								<td class="hidden-phone"><span class=""
									style="width: 80%; display: inline-block;"><?php echo $val['banner_alt_text'];?>
								</span></td>
								<td class="hidden-phone"><span class=""
									style="width: 80%; display: inline-block;"><?php echo $val['banner_create_date'];?>
								</span></td>
                                <input type="hidden" id="bannerId" name="bannerId" value="<?php echo $val['banner_id']; ?>" />
								<td class="temp">
                                    <a href="<?php echo '/banner/editbanner/'.$val['banner_id'];?>" title="Edit banner" id="banEdit">
                                            <button class="btn btn-primary btn-xs editBanner">
                                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                            </button>
                                    </a>
									        <button class="btn btn-danger btn-xs delBanner" title="Delete banner" data-id="<?php echo $val['banner_id']; ?>" >
										        <i class="fa fa-trash-o"></i>
									        </button>

                                            <button class="btn btn-primary btn-xs temp_hide" data-id="<?php echo $i; ?>" title="Hide banner" <?php if(($val['banner_isVisible'] == '1')){ echo "style='display: inline;'";} else{ echo "style='display: none;'";}?> >Hide</button>
                                            <button class="btn btn-primary btn-xs temp_show" data-id="<?php echo $i; ?>" title="Show banner" <?php if(($val['banner_isVisible'] == '1')){ echo "style='display: none;'";} else{ echo "style='display: inline;'";}?> >Show</button>

								</td>
							</tr>
							<?php }
                            }
							else
							{ ?>

                            <tr	class="manageAll tempId">
                                <td></td>
                                <td>
                                    <label style="float: right;"><?php echo "No records found..."; ?></label>
                                </td>
                                <td></td>
                                <td></td>
                            </tr>

							<?php }?>
						</tbody>
					</table>
				</div>
				<!-- /content-panel -->
			</div>
			<!-- /col-md-12 -->
		</div>
		<!-- /row -->

	</section>
	<!-- /wrapper -->

	<!--delete popup-->
	<section id="dynamicpagecreatepopup" class="popupFormForDynamicPage chang_PPopup_conta">
	<div id="" class="chang_PPopup">
    <div class="tab-content" style="border:0px solid;width:490px;">
		<form class="form-popup" style="margin-top: 0px;" method="POST" action="/banner/delbanner" enctype="multipart/form-data">
			 <a class="close" href="javascript:void(0)" onclick="$('#dynamicpagecreatepopup').hide();" style="margin: 10px 10px 0 0px;"><i aria-hidden="true" class="fa fa-times"></i></a>
			<h2 class="form-login-heading">Delete Banner</h2>
			<div class="login-wrap" style="overflow:hidden;text-align:center;">
				<input type="hidden" name="hidden_id" value="" class="hidden_id" id="hidden_userid">
				<h4 class="form-login-heading">Are you sure you want to delete this banner?</h4>
				<div style="overflow:hidden;display:inline-block;">
                    <input type="button" class="popup_cancel" onclick="$('#dynamicpagecreatepopup').hide();" id="btn"  value="CANCEL"/>
					<input type="submit" class="popup_ok" value="OK"/>
				</div>
			</div>
		</form>
	</div>
    <!--tab-content-->
    </div>
    </section>
    <!-- /delete popup-->

    <!--hide-template popup-->
	<section id="dynamichidecreatepopup" class="popupFormForDynamicPage chang_PPopup_conta">
	<div id="" class="chang_PPopup">
    <div class="tab-content" style="border:0px solid;width:490px;">
			 <a class="close" href="javascript:void(0)" onclick="$('#dynamichidecreatepopup').hide();" style="margin: 10px 10px 0 0px;"><i aria-hidden="true" class="fa fa-times"></i></a>
			 <div class="form-popup" style="margin-top: 0px;">
			 <h2 class="form-login-heading">Hide Banner</h2>
			 <div class="login-wrap" style="overflow:hidden;text-align:center;">
				<input type="hidden" name="hidden_id" value="" class="hidden_id" id="hidden_dataid_hide">
				<h4 class="form-login-heading">Are you sure you want to hide this banner?</h4>
				<div style="overflow:hidden;display:inline-block;">
                    <input type="button" class="popup_cancel" onclick="$('#dynamichidecreatepopup').hide();" id="btn"  value="CANCEL"/>
					<input type="button" class="popup_ok hideTemplate" id="hideTemplate" value="OK"/>
					<input type="hidden" name="hidden_tempid" value="" class="hidden_tempid" id="hidden_tempid_hide" />
				</div>
			</div>
            </div>
	</div>
    <!--tab-content-->
    </div>
    </section>
    <!-- /hide-template popup-->

    <!--show-template popup-->
	<section id="dynamicshowcreatepopup" class="popupFormForDynamicPage chang_PPopup_conta">
	<div id="" class="chang_PPopup">
    <div class="tab-content" style="border:0px solid;width:490px;">
			 <a class="close" href="javascript:void(0)" onclick="$('#dynamicshowcreatepopup').hide();" style="margin: 10px 10px 0 0px;"><i aria-hidden="true" class="fa fa-times"></i></a>
            <div class="form-popup" style="margin-top: 0px;">
			<h2 class="form-login-heading">Show Banner</h2>
			<div class="login-wrap" style="overflow:hidden;text-align:center;">
				<input type="hidden" name="hidden_id" value="" class="hidden_id" id="hidden_dataid_show">
				<h4 class="form-login-heading">Are you sure you want to show this banner?</h4>
				<div style="overflow:hidden;display:inline-block;">
                    <input type="button" class="popup_cancel" onclick="$('#dynamicshowcreatepopup').hide();" id="btn"  value="CANCEL"/>
					<input type="button" class="popup_ok showTemplate" id="showTemplate" value="OK"/>
					<input type="hidden" name="hidden_tempid" value="" class="hidden_tempid" id="hidden_tempid_show" />
				</div>
			</div>
            </div>
	</div>
    <!--tab-content-->
    </div>
    </section>
    <!-- /show-template popup-->
</section>
<!-- /MAIN CONTENT -->
