<!--main content start-->
<section id="main-content">
<section class="wrapper">
<!-- SORTABLE TO DO LIST -->
<div class="row mt mb">
    <div class="col-md-12">
              <section class="task-panel tasks-widget">
                <div class="panel-heading">
                    <div class="pull-left"><h5><i class="fa fa-tasks"></i> General terms and condition manager </h5></div>
                    <br>
                </div>
                  <div class="panel-body">
                      <div class="task-content">
                          <ul id="sortable" class="task-list TC-lists">
                              <?php foreach($TCList as $eachTC){ ?>
                              <li class="list-primary" data-orderconnect="<?php echo $eachTC->id; ?>">
                                  <i class=" fa fa-ellipsis-v"></i>

                                  <div class="task-title">
                                      <span class="task-title-sp"><?php echo $eachTC->text; ?></span>
                                      <div class="pull-right hidden-phone">
                                          <button class="btn btn-success btn-xs fa fa-check" style="display:none;"></button>
                                          <button class="btn btn-primary btn-xs fa fa-pencil"></button>
                                          <button class="btn btn-danger btn-xs fa fa-trash-o"></button>
                                      </div>
                                  </div>
                                  <div class="task-edit">
                                      <input type="text" value="<?php echo $eachTC->text; ?>" name="TCtext" />
                                  </div>
                              </li>
                              <?php } ?>
                          </ul>
                      </div>
                      <div class="add-task-row" style="text-align:center;">
                          <a class="btn btn-default btn-sm pull-left TC-dashboard-add" href="javascript:void(0)">Add New</a>
                      </div>
                  </div>
              </section>
          </div><!--/terms and condition section ended -->
  </div><!-- /row -->
</section><! --/wrapper -->
</section><!-- /MAIN CONTENT -->
<!--main content end-->
