<div class="container">
	<div class="row">
		<div class="col-lg-3 col-sm-6">

            <div class="card hovercard">
                <div class="avatar">
                    <img alt="" src="http://lorempixel.com/100/100/people/9/">
                </div>
                <div class="info">
                    <div class="title">
                        <p><?php echo $data[0]['first_name']." ".$data[0]['last_name'] ;?></p>
                    </div>
                    <div class="desc">Passionate designer</div>
                    <div class="desc">Curious developer</div>
                    <div class="desc">Tech geek</div>
                    <div class="desc"><a href="<?php echo $dynamicPath."/corp/logout";?>">Logout</a></div>
                </div>
               
            </div>

        </div>

	</div>
</div>