<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Show album">
    <meta name="keyword" content="Show album, Show albums, album, albums">
</head>
<body>
    <?php
    //include 'navbar.phtml';
    echo $this->content;
    ?>

</body>
</html>
