<?php

$controller = strtolower($controller);
$action = strtolower($action);
$t = time();
if($action==""){$action = "index";}
switch ($controller) {
    case 'corp':
        switch ($action) {
            case 'index':
                $this->headScript()
                    ->prependFile($this->basePath() . '/js/Corporateadmin/main.js?version=' . $t)
                    ->prependFile($this->basePath() . '/js/common/jquery.placeholder.js?version=' . $t);
                break;

            default:
                break;
        }
       

    default:
        break;
}
echo $this->headScript()
        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js');
?>



