<!--main content start-->
<section id="main-content">
<section class="wrapper">
<!-- SORTABLE TO DO LIST -->
<div class="row mt mb">
    <div class="col-md-12">
              <section class="task-panel tasks-widget">
                <div class="panel-heading">
                    <div class="pull-left"><h5><i class="fa fa-tasks"></i> Header menu </h5></div>
                    <br>
                </div>
                  <div class="panel-body">
                      <div class="task-content">
                          <ul id="sortable" class="task-list header-menu-sortable">
                              <?php foreach($headerMenu as $eachMenu){ ?>
                              <li class="list-primary" data-orderconnect="<?php echo $eachMenu->menu_id; ?>" data-order="<?php echo $eachMenu->rank; ?>">
                                  <i class=" fa fa-ellipsis-v"></i>

                                  <div class="task-title">
                                      <span class="task-title-sp"><?php echo $eachMenu->name; ?></span>
                                      <span class="badge bg-success">Link : <?php echo $eachMenu->menuLink; ?></span>
                                      <span class="badge bg-info"><?php echo  ($eachMenu->tab == 0 ? 'Same tab' : 'New tab') ?></span>
                                      <div class="pull-right hidden-phone">
                                          <button class="btn btn-success btn-xs fa fa-check" style="display:none;"></button>
                                          <button class="btn btn-primary btn-xs fa fa-pencil"></button>
                                          <button class="btn btn-danger btn-xs fa fa-trash-o"></button>
                                      </div>
                                  </div>
                                  <div class="task-edit">
                                      <input type="text" value="<?php echo $eachMenu->name; ?>" name="menuTitle" />
                                      <input type="text" value="<?php echo $eachMenu->menuLink; ?>" name="menuUrl" />
                                      <input type="checkbox" <?php echo  ($eachMenu->tab == 0 ? '' : 'checked') ?> /> Check it to open the link in new tab.
                                  </div>
                              </li>
                              <?php } ?>
                          </ul>
                      </div>
                      <div class="add-task-row" style="text-align:center;">
                          <a class="btn btn-default btn-sm pull-left header-menu-add" href="javascript:void(0)">Add New</a>
                          <a class="pull-center header-menu-message" href="javascript:void(0)" style="display:none;">Your changes is not save. Save it!</a>
                          <a class="btn btn-success btn-sm pull-right header-menu-save" href="javascript:void(0)" style="display:none;">Save changes</a>
                      </div>
                  </div>
              </section>
          </div><!--/Header menu section ended -->
    <div class="col-md-12">
              <section class="task-panel tasks-widget">
                <div class="panel-heading">
                    <div class="pull-left"><h5><i class="fa fa-tasks"></i> Corporate info menu </h5></div>
                    <br>
                </div>
                  <div class="panel-body">
                      <div class="task-content">
                          <ul id="sortable" class="task-list primary-footer-menu-sortable">
                              <?php foreach($primaryFooterMenu as $eachMenu){ ?>
                              <li class="list-primary" data-orderconnect="<?php echo $eachMenu->menu_id; ?>" data-order="<?php echo $eachMenu->rank; ?>">
                                  <i class=" fa fa-ellipsis-v"></i>

                                  <div class="task-title">
                                      <span class="task-title-sp"><?php echo $eachMenu->name; ?></span>
                                      <span class="badge bg-success">Link : <?php echo $eachMenu->menuLink; ?></span>
                                      <span class="badge bg-info"><?php echo  ($eachMenu->tab == 0 ? 'Same tab' : 'New tab') ?></span>
                                      <div class="pull-right hidden-phone">
                                          <button class="btn btn-success btn-xs fa fa-check" style="display:none;"></button>
                                          <button class="btn btn-primary btn-xs fa fa-pencil"></button>
                                          <button class="btn btn-danger btn-xs fa fa-trash-o"></button>
                                      </div>
                                  </div>
                                  <div class="task-edit">
                                      <input type="text" value="<?php echo $eachMenu->name; ?>" name="menuTitle" />
                                      <input type="text" value="<?php echo $eachMenu->menuLink; ?>" name="menuUrl" />
                                      <input type="checkbox" <?php echo  ($eachMenu->tab == 0 ? '' : 'checked') ?> /> Check it to open the link in new tab.
                                  </div>
                              </li>
                              <?php } ?>
                          </ul>
                      </div>
                      <div class="add-task-row" style="text-align:center;">
                          <a class="btn btn-default btn-sm pull-left primary-footer-menu-add" href="javascript:void(0)">Add New</a>
                          <a class="pull-center primary-footer-menu-message" href="javascript:void(0)" style="display:none;">Your changes is not save. Save it!</a>
                          <a class="btn btn-success btn-sm pull-right primary-footer-menu-save" href="javascript:void(0)" style="display:none;">Save changes</a>
                      </div>
                  </div>
              </section>
          </div><!--/Primary footer -> corporate info menu section ended -->
    <div class="col-md-12">
              <section class="task-panel tasks-widget">
                <div class="panel-heading">
                    <div class="pull-left"><h5><i class="fa fa-tasks"></i> Your account menu </h5></div>
                    <br>
                </div>
                  <div class="panel-body">
                      <div class="task-content">
                          <ul id="sortable" class="task-list secondary-footer-menu-sortable">
                              <?php foreach($secondaryFooterMenu as $eachMenu){ ?>
                              <li class="list-primary" data-orderconnect="<?php echo $eachMenu->menu_id; ?>" data-order="<?php echo $eachMenu->rank; ?>">
                                  <i class=" fa fa-ellipsis-v"></i>

                                  <div class="task-title">
                                      <span class="task-title-sp"><?php echo $eachMenu->name; ?></span>
                                      <span class="badge bg-success">Link : <?php echo $eachMenu->menuLink; ?></span>
                                      <span class="badge bg-info"><?php echo  ($eachMenu->tab == 0 ? 'Same tab' : 'New tab') ?></span>
                                      <div class="pull-right hidden-phone">
                                          <button class="btn btn-success btn-xs fa fa-check" style="display:none;"></button>
                                          <button class="btn btn-primary btn-xs fa fa-pencil"></button>
                                          <button class="btn btn-danger btn-xs fa fa-trash-o"></button>
                                      </div>
                                  </div>
                                  <div class="task-edit">
                                      <input type="text" value="<?php echo $eachMenu->name; ?>" name="menuTitle" />
                                      <input type="text" value="<?php echo $eachMenu->menuLink; ?>" name="menuUrl" />
                                      <input type="checkbox" <?php echo  ($eachMenu->tab == 0 ? '' : 'checked') ?> /> Check it to open the link in new tab.
                                  </div>
                              </li>
                              <?php } ?>
                          </ul>
                      </div>
                      <div class="add-task-row" style="text-align:center;">
                          <a class="btn btn-default btn-sm pull-left secondary-footer-menu-add" href="javascript:void(0)">Add New</a>
                          <a class="pull-center secondary-footer-menu-message" href="javascript:void(0)" style="display:none;">Your changes is not save. Save it!</a>
                          <a class="btn btn-success btn-sm pull-right secondary-footer-menu-save" href="javascript:void(0)" style="display:none;">Save changes</a>
                      </div>
                  </div>
              </section>
          </div><!--/Secondary footer -> your account menu section ended -->
  </div><!-- /row -->
</section><! --/wrapper -->
</section><!-- /MAIN CONTENT -->
<!--main content end-->
