<div id="login-page">
    <div class="container">
        <form class="form-login" action="" id="adminlogin" method="post">
            <h2 class="form-login-heading">Sign in now</h2>
            <div class="login-wrap">
                <input type="text" name="userId" id="userId" class="form-control" placeholder="User ID" autofocus required>
                <br>
                <input type="password" name="password" id="password" class="form-control" placeholder="Password" required>
                <br>
                <input type="submit" style="background-color: #824181 ; color: #fff;" class="btn btn-theme btn-block" id="submitbtn" value="SIGN IN">
                <label class="col-sm-12 loginError" id="errormsg"></label>
            </div>
        </form>
    </div>
</div>
