<section id="main-content">
      <section class="wrapper">
        <div class="row mt">
            <div class="col-lg-12">
              <div class="form-panel">
                  <h4 class="mb">Add artists</h4>
                  <form class="form-horizontal style-form" action="/ev/saveartist" method="post" enctype="multipart/form-data">
                      <div class="form-group">
                          <label class="col-sm-2 col-sm-2 control-label">Title</label>
                          <div class="col-sm-10">
                              <input type="text" class="form-control" name="artists_title">
                          </div>
                      </div> <!-- artists title -->
                      <div class="form-group">
                          <label class="col-sm-2 col-sm-2 control-label">Description</label>
                          <div class="col-sm-10">
                              <textarea name="artists_desc" class="form-control" style="height:100px;"></textarea>
                          </div>
                      </div> <!-- artists description -->
                      <div class="form-group">
                          <label class="col-sm-2 col-sm-2 control-label">Photo</label>
                          <div class="col-sm-10">
                              <label class="control-label">Upload artist pic</label>
                              <input class="form-control" type="file" name="artistsImage"/>
                          </div>
                      </div> <!-- artists image -->
                      <div class="form-group">
                          <label class="col-sm-2 col-sm-2 control-label">Artist Website</label>
                          <div class="col-sm-10">
                              <input type="text" class="form-control" name="artists_website">
                              <span class="help-block">Enter artist's website link</span>
                          </div>
                      </div> <!-- artists Website -->
                      <div class="form-group">
                          <label class="col-sm-2 col-sm-2 control-label">Artist Soundcloud</label>
                          <div class="col-sm-10">
                              <input type="text" class="form-control" name="artists_soundcloud">
                              <span class="help-block">Enter artist's soundcloud link</span>
                          </div>
                      </div> <!-- artists Soundcloud -->
                      <div class="form-group">
                          <label class="col-sm-2 col-sm-2 control-label">Artist Instagram</label>
                          <div class="col-sm-10">
                              <input type="text" class="form-control" name="artists_instagram">
                              <span class="help-block">Enter artist's instagram link</span>
                          </div>
                      </div> <!-- artists Instagram -->
                      <div class="form-group">
                          <label class="col-sm-2 col-sm-2 control-label">Artist Twitter</label>
                          <div class="col-sm-10">
                              <input type="text" class="form-control" name="artists_twitter">
                              <span class="help-block">Enter artist's twitter link</span>
                          </div>
                      </div> <!-- artists Twitter -->
                      <div class="form-group">
                          <label class="col-sm-2 col-sm-2 control-label">Artist Facebook</label>
                          <div class="col-sm-10">
                              <input type="text" class="form-control" name="artists_facebook">
                              <span class="help-block">Enter artist's facebook page link</span>
                          </div>
                      </div> <!-- artists Facebook -->
                      <div class="form-group">
                          <label class="col-sm-2 col-sm-2 control-label">On tour artists?</label>
                          <div class="col-sm-10">
                              <label>
                                  <input type="radio" name="optionOnTour" value="1"> Yes
                                  <input type="radio" name="optionOnTour" value="0" checked=""> No
						      </label>
                          </div>
                      </div>
                      <div class="form-group">
                          <div class="col-sm-10">
                            <input type="submit" value="Save artist" class="btn btn-success btn-sm" />
                          </div>
                      </div>
                  </form>
              </div>
</div><!-- Event form section-->
        </div><!-- /row -->
      </section><! --/wrapper -->
</section>
