<!--main content start-->
<section id="main-content">
<section class="wrapper">
<!-- SORTABLE TO DO LIST -->
<div class="row mt mb">
    <div class="col-md-12">
              <section class="task-panel tasks-widget">
                <div class="panel-heading">
                    <div class="pull-left"><h5><i class="fa fa-tasks"></i> Events </h5></div>
                    <br>
                </div>
                  <div class="panel-body">
                      <div class="task-content">
                          <ul id="sortable" class="task-list event-sortable">
                              <?php foreach($eventList as $eachEvent){
                              $location = json_decode($eachEvent->event_location, true);
                              $artists = json_decode($eachEvent->event_artists, true);
                              if (isset($artistId) && ($pos = array_search($artistId, $artists)) === false)
                                continue;
                              ?>
                              <li class="list-primary" data-orderconnect="<?php echo $eachEvent->event_id; ?>" data-order="<?php echo $eachEvent->event_rank; ?>">
                                  <i class=" fa fa-ellipsis-v"></i>

                                  <div class="task-title">
                                      <span class="task-title-sp"><?php echo $eachEvent->event_title; ?></span>
                                      <span class="badge bg-success">Location : <?php echo $location['address'] .":".$location['city/town']; ?></span>
                                      <div class="pull-right hidden-phone">
                                          <?php if (!isset($artistId)){ ?>
                                          <a href="/ev/edit/<?php echo $eachEvent->event_id; ?>">
                                              <button class="btn btn-primary btn-xs fa fa-pencil"></button>
                                          </a>
                                          <?php } ?>
                                          <a target="_blank" href="/event/<?php echo $eachEvent->event_id; ?>">
                                              <button class="btn btn-primary btn-xs fa fa-eye"></button>
                                          </a>

                                          <a href="/ev/eventticket/<?php echo $eachEvent->event_id; ?>">
                                              <button class="btn btn-primary btn-xs fa fa-ticket"></button>
                                          </a>

                                          <?php if (!isset($artistId)){ ?>
                                          <a href="/user/booking/event_id/<?php echo $eachEvent->event_id; ?>">
                                              <button title="View booking for this event" class="btn btn-primary btn-xs fa fa-arrow-right"></button>
                                          </a>
                                          <button class="btn btn-danger btn-xs fa fa-trash-o event-trash"></button>
                                          <?php } ?>

                                      </div>
                                  </div>
                              </li>
                              <?php } ?>
                          </ul>
                      </div>
                      <?php if (!isset($artistId)){ ?>
                      <div class="add-task-row" style="text-align:center;">
                          <a class="btn btn-default btn-sm pull-left" href="/ev/add">Add New</a>
                      </div>
                      <?php } ?>
                  </div>
              </section>
          </div><!--/Header menu section ended -->
  </div><!-- /row -->
</section><! --/wrapper -->
</section><!-- /MAIN CONTENT -->
<!--main content end-->
