<section id="main-content">
          <section class="wrapper site-min-height">
          	<h3><i class="fa fa-angle-right"></i> Gallery</h3>
          	<hr>
                <div class="progress">
				    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">0%</div>
                </div>
                <div align="center">
                    <div id="dock" class="dock">Drag & Drop Photos Here</div>
                </div>
				<div class="row mt mediaElement">
                    <?php foreach($images as $eachImageFromDirectory) {?>
					<div class="desc">
						<div class="project-wrapper">
		                    <div class="project">
		                        <div class="photo-wrapper">
		                            <div class="photo">
		                            	<a class="fancybox" href="<?php echo $eachImageFromDirectory ?>"><img class="img-responsive" src="<?php echo $eachImageFromDirectory ?>" alt=""></a>
		                            </div>
		                            <div class="overlay"></div>
		                        </div>
		                    </div>
		                </div>
					</div><!-- col-lg-4 -->
					<?php } ?>
					</div><!-- /row -->

		</section><! --/wrapper -->
      </section>
